# Generated by Django 6.0.6 on 2026-06-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('sold_out', 'Sold out'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='paused', max_length=20),
        ),
    ]
