# Generated by Django 6.0.6 on 2026-06-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
